SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE OA_ARTICLERANGE;
DROP TABLE OA_ARTICLEREAD;
DROP TABLE OA_ARTICLE;
DROP TABLE OA_ARTICLECATE;
DROP TABLE OA_DOCRANGE;
DROP TABLE OA_DOCUMENT;
DROP TABLE OA_DOCCATE;
DROP TABLE OA_FILEBOX;
DROP TABLE OA_HOLIDAY;
DROP TABLE OA_TEAMUSER;
DROP TABLE OA_TEAM;




/* Create Tables */

-- 包含个人及公共文章
CREATE TABLE OA_ARTICLE
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	TITLE VARCHAR(200) COMMENT '标题',
	SUMMARY VARCHAR(500) COMMENT '摘要',
	CONTENT LONGTEXT COMMENT '内容',
	CTIME VARCHAR(50) COMMENT '创建时间',
	PTIME VARCHAR(50) COMMENT '发布时间',
	CREATER BIGINT NOT NULL COMMENT '创建人',
	STARTTIME VARCHAR(50) COMMENT '开始日期',
	-- yyyy-MM-dd HH:mm:ss
	ENDTIME VARCHAR(50) COMMENT '结束日期',
	ACTCATEID BIGINT NOT NULL COMMENT '文章分类id',
	-- 0：私有 1:指定范围 2 公开
	VRANGE SMALLINT COMMENT '可查阅范围',
	UPDATER BIGINT COMMENT '修改人',
	UTIME VARCHAR(50) COMMENT '修改时间',
	PRIMARY KEY (ID)
) COMMENT = '文章' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_ARTICLECATE
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CNAME VARCHAR(50) COMMENT '名称',
	NUM VARCHAR(20) COMMENT '编号',
	REMARK VARCHAR(100) COMMENT '备注',
	PID BIGINT NOT NULL COMMENT '父级分类id',
	ORDERNUM INT COMMENT '排序顺序',
	PRIMARY KEY (ID)
) COMMENT = '文章分类' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_ARTICLERANGE
(
	ARTID BIGINT NOT NULL COMMENT '文章id',
	-- 如角色、部门、机构、人员id
	OBJID BIGINT COMMENT '范围对象id',
	-- 0人员1角色2部门3机构
	OBJTYPE SMALLINT COMMENT '对象类型'
) COMMENT = '文章阅读范围' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_ARTICLEREAD
(
	ARTID BIGINT NOT NULL COMMENT '文章',
	EMPID BIGINT NOT NULL COMMENT '人员id'
) COMMENT = '文章阅读记录' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_DOCCATE
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CNAME VARCHAR(50) COMMENT '名称',
	NUM VARCHAR(20) COMMENT '编号',
	REMARK VARCHAR(100) COMMENT '备注',
	PID BIGINT NOT NULL COMMENT '父级分类id',
	ORDERNUM INT COMMENT '排序顺序',
	PRIMARY KEY (ID)
) COMMENT = '文档分类' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_DOCRANGE
(
	DOCID BIGINT NOT NULL COMMENT '文档id',
	-- 如角色、部门、机构、人员id
	OBJID BIGINT COMMENT '范围对象id',
	-- 0人员1角色2部门3机构
	OBJTYPE SMALLINT COMMENT '对象类型'
) COMMENT = '文档阅读范围' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_DOCUMENT
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	TITLE VARCHAR(200) COMMENT '标题',
	SUMMARY VARCHAR(500) COMMENT '摘要',
	CTIME VARCHAR(50) COMMENT '创建时间',
	PTIME VARCHAR(50) COMMENT '发布时间',
	STARTTIME VARCHAR(50) COMMENT '开始日期',
	-- yyyy-MM-dd HH:mm:ss
	ENDTIME VARCHAR(50) COMMENT '结束日期',
	DOCCATEID BIGINT NOT NULL COMMENT '文档分类id',
	-- 0：私有 1:指定范围 2 公开
	VRANGE SMALLINT COMMENT '可查阅范围',
	CREATER BIGINT NOT NULL COMMENT '创建人',
	-- 多文件格式为:
	-- filename:path;filename:path;
	ATTACHMENT VARCHAR(500) COMMENT '附件',
	UPDATER BIGINT COMMENT '修改人',
	UTIME VARCHAR(50) COMMENT '修改时间',
	PRIMARY KEY (ID)
) COMMENT = '文档' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_FILEBOX
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	-- 上传时候的文件名称，及原始名称
	FILENAME VARCHAR(50) NOT NULL COMMENT '文件名称',
	-- uuid
	FILEPATH VARCHAR(50) NOT NULL COMMENT '文件保存名称',
	UID BIGINT NOT NULL COMMENT '用户',
	DIRID BIGINT COMMENT '目录id',
	CTIME DATETIME NOT NULL COMMENT '上传时间',
	SIZE FLOAT(10,0) COMMENT '文件大小(MB)',
	-- img 图片
	-- music 
	-- file 
	FTYPE VARCHAR(10) COMMENT '文件类型',
	PRIMARY KEY (ID)
) COMMENT = '文件站' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_HOLIDAY
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	TITLE VARCHAR(200) COMMENT '标题',
	-- yyyy-MM-dd
	STARTDATE VARCHAR(10) NOT NULL COMMENT '开始时间',
	-- yyyy-MM-dd
	ENDDATE VARCHAR(10) NOT NULL COMMENT '结束时间',
	-- yyyy-MM-dd
	STARTDATETIAO VARCHAR(10) COMMENT '调整时间',
	-- yyyy-MM-dd
	ENDDATETIAO VARCHAR(10) COMMENT '调整结束时间',
	PRIMARY KEY (ID)
) COMMENT = '假期时间表' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_TEAM
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CNAME VARCHAR(50) NOT NULL COMMENT '团队组织名称',
	REMARK VARCHAR(100) COMMENT '备注',
	PRIMARY KEY (ID)
) COMMENT = '团队组织' DEFAULT CHARACTER SET utf8;


CREATE TABLE OA_TEAMUSER
(
	TEAMID BIGINT NOT NULL COMMENT '团队ID',
	UID BIGINT COMMENT '组员id',
	-- 0：否
	-- 1：是
	LEADER SMALLINT DEFAULT 0 COMMENT '是否负责人'
) COMMENT = '团队人员' DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE OA_ARTICLERANGE
	ADD FOREIGN KEY (ARTID)
	REFERENCES OA_ARTICLE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OA_ARTICLEREAD
	ADD FOREIGN KEY (EMPID)
	REFERENCES OA_ARTICLE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OA_ARTICLE
	ADD FOREIGN KEY (ACTCATEID)
	REFERENCES OA_ARTICLECATE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OA_ARTICLECATE
	ADD FOREIGN KEY (PID)
	REFERENCES OA_ARTICLECATE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OA_DOCCATE
	ADD FOREIGN KEY (PID)
	REFERENCES OA_DOCCATE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OA_DOCUMENT
	ADD FOREIGN KEY (DOCCATEID)
	REFERENCES OA_DOCCATE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OA_DOCRANGE
	ADD FOREIGN KEY (DOCID)
	REFERENCES OA_DOCUMENT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OA_TEAMUSER
	ADD FOREIGN KEY (TEAMID)
	REFERENCES OA_TEAM (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



