SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE OA_BWLPINGLUN;
DROP TABLE OA_BWLSHARE;
DROP TABLE OA_BEIWANGLU;




/* Create Tables */

CREATE TABLE OA_BEIWANGLU
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	TITLE VARCHAR(50) COMMENT '标题',
	CONTEXT LONGTEXT COMMENT '内容',
	CTIME DATETIME COMMENT '创建时间',
	CREATER BIGINT COMMENT '创建人',
	TXPL SMALLINT DEFAULT 0 COMMENT '提醒频率',
	TXDATE DATETIME COMMENT '提醒日期',
	-- 1:本人
	TXBR SMALLINT DEFAULT 0 COMMENT '提醒本人',
	-- 1:只提醒所有共享人 员
	TXSHARE SMALLINT COMMENT '提醒所有共享人',
	-- 1
	IMTX SMALLINT COMMENT '即时通讯提醒',
	-- 1
	EMAILTX SMALLINT COMMENT 'email提醒',
	-- 1
	SMSTX SMALLINT COMMENT '短信提醒',
	PRIMARY KEY (ID)
) COMMENT = '备忘录';


CREATE TABLE OA_BWLPINGLUN
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	BWLID BIGINT NOT NULL COMMENT '备忘录id',
	UID BIGINT COMMENT '评论人',
	PLTIME DATETIME COMMENT '评论时间',
	CONTEXT LONGTEXT COMMENT '内容',
	PRIMARY KEY (ID)
) COMMENT = '备忘录评论';


CREATE TABLE OA_BWLSHARE
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	BWLID BIGINT NOT NULL COMMENT '备忘录id',
	UID BIGINT COMMENT '共享用户id',
	PRIMARY KEY (ID)
) COMMENT = '备忘录共享';



/* Create Foreign Keys */

ALTER TABLE OA_BWLPINGLUN
	ADD FOREIGN KEY (BWLID)
	REFERENCES OA_BEIWANGLU (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OA_BWLSHARE
	ADD FOREIGN KEY (BWLID)
	REFERENCES OA_BEIWANGLU (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



