SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE OA_WEIBOPL;
DROP TABLE OA_WEIBO;




/* Create Tables */

CREATE TABLE OA_WEIBO
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	UID BIGINT COMMENT '发布人',
	-- 长度不能超过280个中文
	CONTEXT VARCHAR(600) COMMENT '内容',
	CDATE DATETIME COMMENT 'cdate',
	ZAN INT COMMENT '赞次数',
	ZHUAN INT COMMENT '转播次数',
	CANG INT COMMENT '收藏次数',
	PRIMARY KEY (ID)
) COMMENT = '微博';


CREATE TABLE OA_WEIBOPL
(
	UID BIGINT COMMENT '用户id',
	CDATE DATETIME COMMENT 'cdate',
	-- 不能多于280中文
	CONTEXT VARCHAR(600) COMMENT 'context',
	ZAN INT COMMENT '赞次数',
	WID BIGINT NOT NULL UNIQUE COMMENT '微博id',
	-- 发布人是否查看该评论
	ISSHOW SMALLINT COMMENT '查看评论',
	CUID BIGINT COMMENT '微博创建人id'
) COMMENT = '微博评论';



/* Create Foreign Keys */

ALTER TABLE OA_WEIBOPL
	ADD FOREIGN KEY (WID)
	REFERENCES OA_WEIBO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



