SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE OA_WORKREPORTMB;




/* Create Tables */

CREATE TABLE OA_WORKREPORTMB
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	PARTMENTID BIGINT NOT NULL COMMENT '部门id',
	-- 0:日报
	-- 1:周报
	-- 2:月报
	-- 3:年报
	TYPE SMALLINT DEFAULT 0 NOT NULL COMMENT '类型',
	CTIME DATETIME COMMENT '创建时间',
	CONTENT LONGTEXT COMMENT '内容',
	PRIMARY KEY (ID)
) COMMENT = '工作日报模版';



