SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE OA_MSG;
DROP TABLE OA_RECVMSG;




/* Create Tables */

-- 发送信息
CREATE TABLE OA_MSG
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	TITLE VARCHAR(100) NOT NULL COMMENT '标题',
	SENDER BIGINT COMMENT '发件人',
	CTIME DATETIME COMMENT '创建时间',
	CONTENT LONGTEXT COMMENT '内容',
	-- 0：已取消
	-- 1：筹划中
	-- 2：进行中
	-- 3：归档
	STAT SMALLINT(1) DEFAULT 1 COMMENT '状态',
	PRIMARY KEY (ID)
) COMMENT = '站内消息';


CREATE TABLE OA_RECVMSG
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	TITLE VARCHAR(100) NOT NULL COMMENT '标题',
	SENDER BIGINT COMMENT '发件人',
	CTIME DATETIME COMMENT '创建时间',
	CONTENT LONGTEXT COMMENT '内容',
	-- 0：已取消
	-- 1：筹划中
	-- 2：进行中
	-- 3：归档
	STAT SMALLINT(1) DEFAULT 1 COMMENT '状态',
	UID BIGINT NOT NULL COMMENT '接收人',
	PRIMARY KEY (ID)
) COMMENT = '接收消息';



