SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE OA_KAOQING;
DROP TABLE OA_KQSET;




/* Create Tables */

CREATE TABLE OA_KAOQING
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	UID BIGINT NOT NULL COMMENT '用户id',
	QDTIME DATETIME NOT NULL COMMENT '签到时间',
	QTTIME DATETIME COMMENT '签退时间',
	-- yyyy-MM-dd
	KQRQ VARCHAR(10) NOT NULL COMMENT '考勤日期',
	MONTH SMALLINT NOT NULL COMMENT '月份',
	DAY SMALLINT NOT NULL COMMENT '日',
	YEAR SMALLINT NOT NULL COMMENT '年',
	QDIP VARCHAR(20) NOT NULL COMMENT '签到ip',
	QTIP VARCHAR(20) COMMENT '签退IP',
	LEGAL SMALLINT COMMENT '是否有效',
	QDTIME1 DATETIME COMMENT '补签到时间',
	QTTIME1 DATETIME COMMENT '补签退时间',
	REMARK VARCHAR(50) COMMENT '补签说明',
	-- 此为考勤负责人
	BQUID BIGINT COMMENT '补签人',
	BEIZHU VARCHAR(50) COMMENT '签到备注',
	PRIMARY KEY (ID)
) COMMENT = '考勤';


CREATE TABLE OA_KQSET
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	Z1 SMALLINT DEFAULT 1 COMMENT '周一',
	Z2 SMALLINT DEFAULT 1 COMMENT '周二',
	Z3 SMALLINT DEFAULT 1 COMMENT '周三',
	Z4 SMALLINT DEFAULT 1 COMMENT '周四',
	Z5 SMALLINT DEFAULT 1 COMMENT '周五',
	Z6 SMALLINT DEFAULT 0 COMMENT '周六',
	Z7 SMALLINT DEFAULT 0 COMMENT '周日',
	-- HH:mm
	STARTTIME TIME COMMENT '上班是时间',
	-- HH:mm
	ENDTIME TIME COMMENT '下班时间',
	-- yyyy-MM-dd
	EXCTDATE DATE COMMENT '执行日期',
	PRIMARY KEY (ID)
) COMMENT = '考勤设置';



