SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE OA_EMAILBOX;
DROP TABLE OA_EMAILSET;




/* Create Tables */

CREATE TABLE OA_EMAILBOX
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	TITLE VARCHAR(100) NOT NULL COMMENT '标题',
	CONTENT LONGTEXT NOT NULL COMMENT '内容',
	UID BIGINT NOT NULL COMMENT 'uid',
	SETID BIGINT NOT NULL COMMENT '邮箱设置id',
	-- {'m':'loyin@loyin.net','n':'龙影'}
	MAILFROM VARCHAR(50) COMMENT '发件人',
	-- [{'m':'loyin@loyin.net','n':'龙影'}]
	MAILTO VARCHAR(1000) COMMENT '收件人',
	-- [{'m':'loyin@loyin.net','n':'龙影'}]
	BCC VARCHAR(500) COMMENT '抄送人',
	-- [{'m':'loyin@loyin.net','n':'龙影'}]
	CC VARCHAR(100) COMMENT '密抄',
	ISNEW BIT(1) DEFAULT '0' COMMENT '是否新邮件',
	MAILDATE DATETIME COMMENT '邮件日期时间',
	-- 0:收件箱
	-- 1:发件箱
	-- 2:草稿箱
	-- 3:已删除
	BOX SMALLINT(1) DEFAULT 0 NOT NULL COMMENT '文件夹',
	-- [{'f':'附件实际名称及目录','n':'附件显示名称'}]
	ATTACHMENT LONGTEXT COMMENT 'attachment',
	HASATTACH BIT(0) DEFAULT '0' COMMENT '是否有附件',
	REPLYSIGN BIT(0) COMMENT '是否回复',
	PRIMARY KEY (ID),
	CONSTRAINT idx_maillist_uniq UNIQUE (TITLE, UID, MAILFROM, MAILTO, MAILDATE, BOX)
) COMMENT = '邮件';


CREATE TABLE OA_EMAILSET
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CNAME VARCHAR(30) NOT NULL COMMENT '昵称',
	EMAIL VARCHAR(100) NOT NULL UNIQUE COMMENT '邮箱',
	UID BIGINT NOT NULL UNIQUE COMMENT '用户id',
	POP3ADDR VARCHAR(50) COMMENT 'pop3Addr',
	POP3PORT INT DEFAULT 110 COMMENT 'pop3Port',
	SMTPADDR VARCHAR(50) COMMENT 'smtpAddr',
	SMTPPORT INT DEFAULT 25 COMMENT 'smtpPort',
	PWD VARCHAR(50) COMMENT '密码',
	SIGN VARCHAR(500) COMMENT '签名',
	-- 1：可用
	-- 0：停用
	STATUS SMALLINT(1) DEFAULT 1 COMMENT '状态',
	-- 0:不使用
	-- 1:使用
	USESIGN SMALLINT(1) DEFAULT 0 COMMENT '是否使用签名',
	PRIMARY KEY (ID)
) COMMENT = '邮箱设置';



