SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

CREATE TABLE SYS_AREA
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CNAME VARCHAR(20),
	PID BIGINT DEFAULT 0,
	SORTNUM INT DEFAULT 1,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE SYS_KUAIDI
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CNAME VARCHAR(50) NOT NULL,
	HOTLINE VARCHAR(30) NOT NULL,
	NETTEL VARCHAR(30) NOT NULL,
	KDYNAME VARCHAR(10) NOT NULL,
	KDYTEL VARCHAR(30) NOT NULL,
	SORTNUM SMALLINT,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE SYS_LOGINLOG
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	UID BIGINT NOT NULL,
	IP VARCHAR(50) NOT NULL,
	LOGINTIME DATETIME NOT NULL,
	LOGOUTTIME DATETIME,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE SYS_MENU
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	MENUNAME VARCHAR(20) NOT NULL,
	URL VARCHAR(50) NOT NULL,
	-- 菜单类型：0 菜单 1：按钮
	TYPE SMALLINT,
	ICON VARCHAR(50),
	ORDERNUM INT DEFAULT 0,
	SAFECODE VARCHAR(20),
	PID BIGINT,
	-- 0禁用1可用
	ENABLE SMALLINT DEFAULT 1,
	REMARK VARCHAR(255),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE SYS_OPERALOG
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	UID BIGINT NOT NULL,
	CTIME VARCHAR(20) NOT NULL,
	MODELNAME VARCHAR(50),
	-- 删除、添加、修改
	EXCT VARCHAR(10),
	FUNC VARCHAR(20),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


-- 包含 菜肴分类、酒水分类
CREATE TABLE SYS_PARAME
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CNAME VARCHAR(20) NOT NULL,
	VAL VARCHAR(20) NOT NULL,
	-- 具体按系统设计要求来定
	TYPE VARCHAR(20),
	SORTNUM SMALLINT DEFAULT 0,
	REMARK VARCHAR(200),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE SYS_PARTMENT
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CNAME VARCHAR(50),
	REMARK VARCHAR(250),
	NUM VARCHAR(20),
	PID BIGINT NOT NULL,
	FZR BIGINT,
	TEL VARCHAR(30),
	FAX VARCHAR(50),
	EMAIL VARCHAR(50),
	ADDR VARCHAR(100),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE SYS_POST
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CNAME VARCHAR(20),
	REMARK VARCHAR(30),
	SORTNUM SMALLINT,
	PID BIGINT,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE SYS_POWERMENU
(
	-- 对用户、机构、部门、角色来进行配置
	OBJID BIGINT NOT NULL,
	-- 0：用户
	-- 1：角色
	-- 2：部门
	-- 3 : 用户自设常用
	TYPE SMALLINT(1) NOT NULL,
	MENUID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;


-- 角色和职务可以公用
CREATE TABLE SYS_ROLE
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CNAME VARCHAR(20) NOT NULL,
	REMARK VARCHAR(255),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE SYS_USERROLE
(
	USERID BIGINT NOT NULL,
	ROLEID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;



