SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE SALE_TECHTASK;
DROP TABLE SALE_BAOBEI;
DROP TABLE SALE_BAOBEIMOBAN;
DROP TABLE SALE_GENJINFANKUI;
DROP TABLE SALE_GENJIN;
DROP TABLE SALE_RICHENG;




/* Create Tables */

CREATE TABLE SALE_BAOBEI
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CUSTID BIGINT NOT NULL COMMENT '客户id',
	VENDERID BIGINT NOT NULL COMMENT '厂商id',
	PRODCUTID BIGINT NOT NULL COMMENT '产品id',
	-- 0无过期限制
	-- 
	BBGQSJ SMALLINT COMMENT '报备过期时间',
	GUOQITIXING VARCHAR(50) COMMENT '过期提醒',
	ZHUYISHIXIANG VARCHAR(500) COMMENT '注意事项',
	BAOBEIBILL LONGTEXT COMMENT '报备单',
	CTIME DATETIME NOT NULL COMMENT '报备时间',
	UID BIGINT NOT NULL COMMENT '报备人',
	MBID BIGINT NOT NULL COMMENT '模版',
	PRIMARY KEY (ID)
) COMMENT = '报备';


CREATE TABLE SALE_BAOBEIMOBAN
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CNAME VARCHAR(50) NOT NULL COMMENT '模版名称',
	-- 0:word模版
	-- 1：excel模版
	MBTYPE SMALLINT COMMENT '模版类型',
	-- 存放文件路径
	FILEPATH VARCHAR(100) COMMENT 'excel文件',
	CTIME DATETIME COMMENT '创建时间',
	CONTENT LONGTEXT COMMENT '内容',
	PRIMARY KEY (ID)
) COMMENT = '报备模版';


CREATE TABLE SALE_GENJIN
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CUSTID BIGINT NOT NULL COMMENT '客户id',
	CONTACTID BIGINT NOT NULL COMMENT '联系人',
	PHONE VARCHAR(50) COMMENT '联系人电话',
	LIANXIFANGSHI BIGINT NOT NULL COMMENT '联系方式',
	LXDATE DATE NOT NULL COMMENT '联系日期',
	TJPRODUCT VARCHAR(50) COMMENT '推荐产品',
	-- 上传附件
	FANGAN VARCHAR(50) COMMENT '方案',
	-- 1：需要
	NEEDTECH SMALLINT COMMENT '需要技术支持',
	LXRECORD VARCHAR(500) COMMENT '联系记录',
	-- 1:下次联系
	NEXTLX SMALLINT COMMENT '下次联系',
	UID BIGINT COMMENT '跟进销售员id',
	CTIME DATETIME COMMENT '创建时间',
	JSCLJL VARCHAR(50) COMMENT '技术处理记录',
	JSID BIGINT COMMENT '技术员',
	-- 技术人员处理的时间
	JSCLSJ DATETIME COMMENT '技术处理时间',
	PRIMARY KEY (ID)
) COMMENT = '客户跟进';


CREATE TABLE SALE_GENJINFANKUI
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	GJID BIGINT NOT NULL COMMENT '跟进id',
	LXJL VARCHAR(100) COMMENT '联系记录',
	FANKUI VARCHAR(100) COMMENT '反馈',
	PRIMARY KEY (ID)
) COMMENT = '跟进反馈';


CREATE TABLE SALE_RICHENG
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CUSTID BIGINT NOT NULL COMMENT '客户id',
	CONTACTID BIGINT NOT NULL COMMENT '联系人',
	UID BIGINT COMMENT '员工id',
	SUBJECT VARCHAR(50) NOT NULL COMMENT '主题',
	-- 1：出差
	-- 2：
	RCLX BIGINT NOT NULL COMMENT '日程类型',
	-- yyyy-MM-dd
	STARTDATE VARCHAR(10) COMMENT '具体开始日期',
	ENDTIME DATETIME NOT NULL COMMENT '结束时间',
	-- 0:不需要审核时状态
	-- 1:提交审核
	-- 2:审核通过
	-- 3:审核拒绝
	STAT SMALLINT DEFAULT 0 NOT NULL COMMENT '审核状态',
	JINZHAN VARCHAR(50) COMMENT '进展',
	-- 0:待审核
	-- 1:日程安排（不需要审核）
	TYPE SMALLINT DEFAULT 0 NOT NULL COMMENT '审核状态',
	SHENHREN BIGINT COMMENT '审核人',
	SHTIME DATETIME COMMENT '审核时间',
	CONTENT VARCHAR(500) COMMENT '内容',
	FEIYONG FLOAT COMMENT '费用',
	SHENHYJ VARCHAR(500) COMMENT '审核意见',
	PRIMARY KEY (ID)
) COMMENT = '日程';


CREATE TABLE SALE_TECHTASK
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CONTACTID BIGINT NOT NULL COMMENT '联系人',
	LIANXIFANGSHI BIGINT NOT NULL COMMENT '联系方式',
	GENJINJC BIGINT NOT NULL COMMENT '跟进进程',
	-- yyyy-MM-dd
	LXRQ VARCHAR(10) NOT NULL COMMENT '联系日期',
	ZCLX BIGINT NOT NULL COMMENT '支持类型',
	XWCSJ DATETIME COMMENT '须完成时间',
	-- 0:不需要
	-- 1:需要
	NEEDTECH SMALLINT COMMENT '需技术支持',
	JSLXR BIGINT NOT NULL COMMENT '技术联系人',
	RWLY BIGINT COMMENT '任务来源',
	JSXQ LONGTEXT COMMENT '技术需求',
	LXJL LONGTEXT COMMENT '联系记录',
	TJPRODUCT VARCHAR(50) COMMENT '推荐产品',
	-- 1:下次联系
	NEXTLX SMALLINT COMMENT '下次联系',
	CUSTID BIGINT NOT NULL COMMENT '客户id',
	-- 0:未分配
	-- 1:已分配
	TASKSTAT SMALLINT DEFAULT 0 COMMENT '任务状态',
	-- 0:未完成
	-- 1:已完成
	-- 2:否决
	STAT SMALLINT COMMENT '状态',
	-- 0:非常不满意
	-- 1:不满意
	-- 2:满意
	-- 3:非常满意
	FKPJ SMALLINT COMMENT '反馈评价',
	CLSM LONGTEXT COMMENT '处理说明',
	XSFK LONGTEXT COMMENT '销售反馈',
	TJTIME DATETIME NOT NULL COMMENT '提交时间',
	PRIMARY KEY (ID)
) COMMENT = '技术任务';



/* Create Foreign Keys */

ALTER TABLE SALE_TECHTASK
	ADD FOREIGN KEY (CUSTID)
	REFERENCES SALE_BAOBEI (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SALE_BAOBEI
	ADD FOREIGN KEY (MBID)
	REFERENCES SALE_BAOBEIMOBAN (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SALE_GENJINFANKUI
	ADD FOREIGN KEY (GJID)
	REFERENCES SALE_GENJIN (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



