SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE CRM_CUSTSALE;
DROP TABLE CRM_XYCP;
DROP TABLE CRM_CUSTOMER;
DROP TABLE CRM_CUSTTYPE;




/* Create Tables */

CREATE TABLE CRM_CUSTOMER
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CNAME VARCHAR(50) NOT NULL COMMENT '客户名称',
	JCNAME VARCHAR(50) NOT NULL COMMENT '别名',
	CTYPE BIGINT NOT NULL COMMENT '客户类型',
	KHLY BIGINT COMMENT '客户来源',
	GZDJ BIGINT NOT NULL COMMENT '跟踪进度',
	HANGYE BIGINT COMMENT '所属行业',
	ZYBIZ VARCHAR(50) COMMENT '主营业务',
	PROVINCE BIGINT NOT NULL COMMENT '省份',
	CITY BIGINT NOT NULL COMMENT '城市',
	ADDR VARCHAR(100) COMMENT '公司地址',
	JTLX VARCHAR(100) COMMENT '交通路线',
	WLGM BIGINT NOT NULL COMMENT '网络规模',
	FWQSL SMALLINT COMMENT '服务器数量',
	WEBSITE VARCHAR(100) COMMENT '公司网址',
	TELPHONE VARCHAR(30) COMMENT '总机电话',
	FAX VARCHAR(30) COMMENT '传真',
	ZIPCODE VARCHAR(10) COMMENT '邮编',
	EMAIL VARCHAR(100) COMMENT 'email',
	KHYH BIGINT COMMENT '开户银行',
	SXZQ BIGINT NOT NULL COMMENT '授信账期',
	BANKACCOUT VARCHAR(50) COMMENT '银行账号',
	XYPJ BIGINT NOT NULL COMMENT '信用评价',
	TAXSNO VARCHAR(50) COMMENT '税号',
	KHYSSJ BIGINT COMMENT '客户预算时间',
	KHFWLX BIGINT NOT NULL COMMENT '客户服务类型',
	GSJJ LONGTEXT COMMENT '公司简介',
	PRIMARY KEY (ID)
) COMMENT = '客户' DEFAULT CHARACTER SET utf8;


CREATE TABLE CRM_CUSTSALE
(
	UID BIGINT NOT NULL COMMENT '销售员id',
	CTIME DATETIME NOT NULL COMMENT '分配时间',
	CUSTID BIGINT NOT NULL COMMENT '客户id'
) COMMENT = '客户分配' DEFAULT CHARACTER SET utf8;


CREATE TABLE CRM_CUSTTYPE
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	CNAME VARCHAR(50) NOT NULL COMMENT '名称',
	DESCRIP VARCHAR(100) COMMENT '描述',
	-- 日（超出此指定时间没有跟进的客户将列入跟进警告，没有限制设置为0）
	GJPL SMALLINT NOT NULL COMMENT '跟进频率',
	-- 日（超出此指定时间后自动变为普通客户，没有限制设置为0）
	JGQX SMALLINT NOT NULL COMMENT '警告期限',
	-- (业务员最多拥有该类型的客户数量，没有限制设置0)
	ZDSL SMALLINT NOT NULL COMMENT '最多数量',
	SORTNUM SMALLINT NOT NULL COMMENT '排序',
	PRIMARY KEY (ID)
) COMMENT = '客户类型' DEFAULT CHARACTER SET utf8;


CREATE TABLE CRM_XYCP
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	PRODCUTTYPE BIGINT NOT NULL COMMENT '产品类型',
	PRONAME VARCHAR(50) NOT NULL COMMENT '产品名称',
	GMSL SMALLINT COMMENT '购买数量',
	-- yyyy-MM-dd
	GMSJ VARCHAR(10) COMMENT '购买日期',
	-- yyyy-MM-dd
	YJGMSJ VARCHAR(10) COMMENT '预计购买日期',
	CUSTID BIGINT NOT NULL COMMENT '客户id',
	PRIMARY KEY (ID)
) COMMENT = '客户现有产品' DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE CRM_CUSTSALE
	ADD FOREIGN KEY (CUSTID)
	REFERENCES CRM_CUSTOMER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CRM_XYCP
	ADD FOREIGN KEY (CUSTID)
	REFERENCES CRM_CUSTOMER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



