SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE SYS_FORMFIELD;
DROP TABLE SYS_FORM;




/* Create Tables */

CREATE TABLE SYS_FORM
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	-- 数据库表名
	TNAME VARCHAR(30) NOT NULL UNIQUE COMMENT '表名',
	ZHUS VARCHAR(30) COMMENT '注释',
	-- 1:主表 2:从表
	TBTYPE SMALLINT DEFAULT 1 NOT NULL COMMENT '表单类型',
	PACKAGE VARCHAR(50) COMMENT '包名',
	LISTADD SMALLINT DEFAULT 0 COMMENT '在grid中添加及修改',
	PRIMARY KEY (ID)
) COMMENT = '表单';


CREATE TABLE SYS_FORMFIELD
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	FMID BIGINT NOT NULL COMMENT '表单id',
	FIELDNAME VARCHAR(20) COMMENT '字段名',
	FIELDDESC VARCHAR(30) COMMENT '字段描述',
	-- 对应html 的 title
	FIELDTITLE VARCHAR(50) COMMENT '字段提示',
	-- String       文本
	-- Integer     整型
	-- Long        长整型
	-- Float         浮点型
	-- Double     双精度
	-- Bigdicms  bigdicme
	-- 
	FTYPE VARCHAR(50) COMMENT '字段类型',
	FLEN SMALLINT NOT NULL COMMENT '字段长度',
	-- 1单行文本
	-- 2多行文本
	-- 3单选
	-- 4复选
	-- 5隐藏
	-- 6下拉框
	-- 7文件上传
	-- 8富文本编辑框
	-- 9角色
	-- 10岗位
	-- 11部门
	CTRLTYPE VARCHAR(50) NOT NULL COMMENT '控件类型',
	VALIT VARCHAR(50) COMMENT '验证规则',
	REQUI SMALLINT DEFAULT 0 COMMENT '必填',
	SHOWINLIST SMALLINT COMMENT '显示到列表',
	SHOWINQRY SMALLINT COMMENT '作为查询条件',
	WFATTR SMALLINT COMMENT '工作流变量',
	SQLSCRIPT LONGTEXT COMMENT 'SQL脚本',
	-- desc
	-- asc
	SORTTYPE VARCHAR(0) COMMENT '排序方式',
	SORTNUM SMALLINT COMMENT '字段排序',
	PRIMARY KEY (ID)
) COMMENT = '表单属性';



/* Create Foreign Keys */

ALTER TABLE SYS_FORMFIELD
	ADD FOREIGN KEY (FMID)
	REFERENCES SYS_FORM (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



