SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE FA_TAXRATE;
DROP TABLE FA_WAGEPAY;




/* Create Tables */

CREATE TABLE FA_TAXRATE
(
	ID BIGINT NOT NULL COMMENT 'id',
	-- yyyy-MM-dd
	STARTDATE VARCHAR(10) NOT NULL COMMENT '开始时间',
	RATE FLOAT NOT NULL COMMENT '费率',
	PRIMARY KEY (ID)
) COMMENT = '税率';


CREATE TABLE FA_WAGEPAY
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	-- 到导入excel完成后进行update操作将empid设置为对应的值
	EMPID BIGINT COMMENT '员工id',
	EMPSNO VARCHAR(20) NOT NULL COMMENT '员工编号',
	EMPNAME VARCHAR(20) NOT NULL COMMENT '员工姓名',
	JBGZ FLOAT NOT NULL COMMENT '基本工资',
	GZTS FLOAT NOT NULL COMMENT '工作天数',
	GWGZ FLOAT NOT NULL COMMENT '岗位工资',
	CANTIE FLOAT NOT NULL COMMENT '餐贴',
	JTBT FLOAT NOT NULL COMMENT '交通补贴',
	TXBT FLOAT NOT NULL COMMENT '通讯补贴',
	-- 不是
	-- 是
	QUANQIN VARCHAR(2) NOT NULL COMMENT '全勤',
	-- 请假天数 精确到小数点后1位
	QJIA FLOAT NOT NULL COMMENT '请假',
	SHEBAO FLOAT NOT NULL COMMENT '社保',
	GJJ FLOAT NOT NULL COMMENT '住房公积金',
	YFGZ FLOAT NOT NULL COMMENT '应发工资',
	YGJJ FLOAT NOT NULL COMMENT '员工基金',
	QT FLOAT NOT NULL COMMENT '其他',
	KCHJ FLOAT NOT NULL COMMENT '扣除合计',
	SFGZ FLOAT NOT NULL COMMENT '实发工资',
	-- yyyy-MM
	YM VARCHAR(7) NOT NULL COMMENT '月份',
	CTIME DATETIME NOT NULL COMMENT '上传时间',
	PARTMENTID BIGINT COMMENT '部门id',
	PRIMARY KEY (ID),
	CONSTRAINT idx_empid_ym_uniq UNIQUE (EMPID, YM)
) COMMENT = '工资发放';



