SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Indexes */

DROP INDEX IDX_EMPLOYEE_PWD ON HR_EMPLOYEE;
DROP INDEX IDX_EMPLOYEE_USERNO ON HR_EMPLOYEE;
DROP INDEX IDX_EMP_PYNAME ON HR_EMPLOYEE;



/* Drop Tables */

DROP TABLE HR_EMPLOYEE;
DROP TABLE HR_WAGES;




/* Create Tables */

CREATE TABLE HR_EMPLOYEE
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	FULLNAME VARCHAR(50) NOT NULL COMMENT '姓名',
	-- 男 女
	GENDER VARCHAR(2) DEFAULT '男' NOT NULL COMMENT '性别',
	USERNO VARCHAR(20) NOT NULL UNIQUE COMMENT '人员编号',
	PWD VARCHAR(50) NOT NULL COMMENT '密码',
	BIRTHDAY VARCHAR(20) NOT NULL COMMENT '生日',
	PHONE VARCHAR(20) COMMENT '手机',
	TELPHONE VARCHAR(30) COMMENT '固话',
	ADDR VARCHAR(100) COMMENT '地址',
	FNAMEPY VARCHAR(50) COMMENT '姓名拼音',
	WORKTIME VARCHAR(30) COMMENT '入职时间',
	NATION VARCHAR(10) DEFAULT '汉' COMMENT '民族',
	IDCARD VARCHAR(20) COMMENT '身份证',
	HOMETOWN SMALLINT COMMENT '籍贯',
	DIPLOMA SMALLINT COMMENT '学历',
	PHOTO VARCHAR(50) COMMENT '照片',
	PARTMENTID BIGINT NOT NULL COMMENT '部门id',
	-- 0离职，1在职、2休假、2出差
	STAT SMALLINT DEFAULT 0 COMMENT '状态',
	REMARK VARCHAR(200) COMMENT '备注',
	-- 可以对厨师等技师做推广介绍用
	RESUME LONGTEXT COMMENT '简介',
	-- yyyy-mm-dd HH:mm:ss
	DIMISSIONTIME VARCHAR(20) COMMENT '离职时间',
	IP VARCHAR(50) COMMENT 'IP',
	LOGINTIME DATETIME COMMENT 'logintime',
	PRIMARY KEY (ID)
) COMMENT = '雇员';


CREATE TABLE HR_WAGES
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	WAGES INT COMMENT '每月工资',
	-- 格式为YYYYMM
	ENMONTH VARCHAR(10) COMMENT '生效月份',
	REMARK VARCHAR(250) COMMENT '备注',
	OPERATER BIGINT COMMENT '操作员id',
	CTIME VARCHAR(50) COMMENT '创建时间',
	EMPID BIGINT NOT NULL COMMENT '员工',
	PRIMARY KEY (ID)
) COMMENT = '薪资';



/* Create Indexes */

CREATE INDEX IDX_EMPLOYEE_PWD ON HR_EMPLOYEE (PWD ASC);
CREATE INDEX IDX_EMPLOYEE_USERNO ON HR_EMPLOYEE (USERNO ASC);
CREATE INDEX IDX_EMP_PYNAME ON HR_EMPLOYEE (FNAMEPY ASC);



